### ISSUE TITLE
Problem with creating a new module

### ISSUE THREAD

**Issue by davidyaha** [DanielMSchmidt/generator-react-native-module#1]
I've followed the quick setup and user yo react-native-module but got this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-react-native-module/generators/app/templates/.editorconfig
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-react-native-module/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-react-native-module/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-react-native-module/generators/app/index.js:37:13)
    at /usr/local/lib/node_modules/generator-react-native-module/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

Might be that the published version on npm is not the last?

Thanks ahead,
David

**Comment by davidyaha** [comment]
Tried installing using this github repo with:

```
npm i -g https://github.com/DanielMSchmidt/generator-react-native-module.git
```

And now it did not throw the error above but yeoman did not generate any file in my directory.
Basically yo asked for the name of my module than exited quietly.

Thanks again,
David

**Comment by DanielMSchmidt** [comment]
Hey, 
Thanks for the feedback, I will try to fix this problem in the next couple days.
